### PR TITLE
Load countries from custom local file

### LINKED ISSUE #60: Uee local file for live data rather than url
As a follow on from https://github.com/OCHA-DAP/hdx-python-country/issues/57, we've been looking into implementing this but as it stands the live data feed can only use a url and not a local file. This works but is a bit awkward. Would you be open to extending this to be able to provide the path to a local, custom file to read the live data from? If so, I would be willing to do a PR for it.

### PR DESCRIPTION
**Pull request by andy-isoc**
Fixes #60

### CODE REVIEW

**Review by mcarans — CHANGES_REQUESTED** [review]
Thanks for your PR! 

I think it would be simpler to allow `_ochaurl` to be either a url or path by adding `allow_local=True` to the first `InputOptions` rather than adding a second variable `_ochapath`. `set_ocha_url` would allow either a url or path (which should be made clear in the documentation). So usage would look like:
```
        Country.set_ocha_url(
            script_dir_plus_file("Countries_UZB_Deleted.csv", TestCountry)
        )
        assert (
            Country.get_iso3_country_code("UZBEKISTAN", use_live=False) is None
        )
```

What do you think? Does that work for you?

**Comment by andy-isoc** [comment]
I did think about that approach initially but I was concerned that it would be a little confusing as the naming `set_ocha_url()` wouldn't reflect the usage (if you pass in a *path*). Also I think we'd still have to set `use_live=True` in that scenario, wouldn't we? Again, that doesn't quite feel right to me as if we're loading from static local data it's not really "live" data.

But happy to change it round to that approach if you feel it's better.

**Comment by mcarans** [comment]
Good point about `use_live`. I'll merge your PR. Thanks for making it.

**Comment by mcarans** [comment]
Released in 3.8.4.

**Pull request merged**
